export const styles = {
  appWrap: { display: 'flex', height: '100vh', background: '#EDEFEF', color: '#1B1D1F' },
  loadingWrap: { height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#15181B' },
  loadingCard: { textAlign: 'center' },
  sidebar: { background: '#15181B', color: '#E7E7E5', display: 'flex', flexDirection: 'column', padding: '16px 12px' },
  brand: { display: 'flex', alignItems: 'center', gap: 10, padding: '4px 8px 16px' },
  brandTitle: { fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 15, letterSpacing: 0.5, color: '#F3F1EC' },
  brandSub: { fontSize: 11, color: '#9A9FA4' },
  groupLabel: { fontSize: 10, textTransform: 'uppercase', letterSpacing: 1, color: '#6B7075', padding: '6px 10px 4px' },
  navItem: { display: 'flex', alignItems: 'center', gap: 10, width: '100%', padding: '8px 10px', background: 'transparent', border: 'none', color: '#C7CACD', borderRadius: 6, cursor: 'pointer', fontSize: 13, marginBottom: 2 },
  navItemActive: { background: '#22262B', color: '#F3F1EC' },
  userCard: { display: 'flex', alignItems: 'center', gap: 10, padding: 10, background: '#1C2024', borderRadius: 8, marginTop: 8 },
  roleStripe: { width: 4, alignSelf: 'stretch', borderRadius: 2 },
  roleStripeSmall: { width: 24, height: 4, borderRadius: 2, margin: '0 auto 4px' },
  userName: { fontSize: 12.5, fontWeight: 600, color: '#F3F1EC', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  userRole: { fontSize: 11, color: '#9A9FA4' },
  logoutBtn: { background: 'transparent', border: 'none', color: '#9A9FA4', cursor: 'pointer', padding: 6 },
  main: { flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 },
  topbar: { display: 'flex', alignItems: 'center', gap: 12, padding: '14px 22px', background: '#FFFFFF', borderBottom: '1px solid #E2E4E5' },
  menuBtn: { background: 'transparent', border: 'none', cursor: 'pointer' },
  topbarTitle: { fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 16 },
  accessPill: { marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 6, padding: '5px 10px', borderRadius: 20, fontSize: 12, fontWeight: 500 },
  content: { flex: 1, overflowY: 'auto' },
  card: { background: '#FFFFFF', border: '1px solid #E2E4E5', borderRadius: 10, padding: 18, marginBottom: 16 },
  cardTitle: { fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 14.5, marginBottom: 12 },
  subTitle: { fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 13, margin: '16px 0 8px', color: '#3E6E91' },
  caption: { fontSize: 12, color: '#6B7075' },
  formGrid: { display: 'grid', gap: 12, alignItems: 'start' },
  label: { display: 'block', fontSize: 11.5, color: '#6B7075', marginBottom: 4, fontWeight: 500 },
  input: { width: '100%', padding: '8px 10px', border: '1px solid #D5D8D9', borderRadius: 6, fontSize: 13, background: '#FBFBFA' },
  eyeBtn: { position: 'absolute', right: 8, top: 30, background: 'transparent', border: 'none', cursor: 'pointer', color: '#6B7075' },
  primaryBtn: { display: 'flex', alignItems: 'center', gap: 6, background: '#E8A324', color: '#1B1D1F', border: 'none', padding: '9px 14px', borderRadius: 6, fontWeight: 600, fontSize: 13, cursor: 'pointer' },
  secondaryBtn: { display: 'flex', alignItems: 'center', gap: 6, background: '#EDEFEF', color: '#1B1D1F', border: '1px solid #D5D8D9', padding: '9px 14px', borderRadius: 6, fontWeight: 600, fontSize: 13, cursor: 'pointer' },
  iconBtn: { background: '#EDEFEF', border: '1px solid #D5D8D9', borderRadius: 6, padding: '4px 8px', cursor: 'pointer', fontSize: 12 },
  iconBtnDanger: { background: '#FBEAE6', border: '1px solid #E7C3B8', color: '#C1462E', borderRadius: 6, padding: '4px 8px', cursor: 'pointer', display: 'flex' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: { textAlign: 'left', padding: '8px 10px', background: '#F5F6F6', color: '#6B7075', fontWeight: 600, fontSize: 11.5, textTransform: 'uppercase', letterSpacing: 0.4, borderBottom: '1px solid #E2E4E5' },
  td: { padding: '9px 10px', borderBottom: '1px solid #EEF0F0' },
  mono: { fontFamily: 'var(--font-mono)', fontSize: 12.5 },
  badge: { padding: '3px 9px', borderRadius: 20, fontSize: 11.5, fontWeight: 600 },
  kpiGrid: { display: 'grid', gap: 14, marginBottom: 16 },
  kpiBox: { background: '#FFFFFF', border: '1px solid #E2E4E5', borderRadius: 10, padding: '16px 18px' },
  kpiLabel: { fontSize: 11.5, color: '#6B7075', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.4 },
  kpiValue: { fontFamily: 'var(--font-display)', fontSize: 26, fontWeight: 700 },
  bigNumber: { fontFamily: 'var(--font-display)', fontSize: 34, fontWeight: 700, color: '#4C8C6B' },
  emptyState: { padding: '24px 0', textAlign: 'center', color: '#9A9FA4', fontSize: 13 },
  checkRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, padding: '4px 0' },
  permLabel: { display: 'flex', alignItems: 'center', gap: 3, cursor: 'pointer' },
  printHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' },
  loginWrap: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#15181B', padding: 20 },
  loginCard: { background: '#FFFFFF', borderRadius: 14, padding: 28, boxShadow: '0 20px 60px rgba(0,0,0,0.35)' },
  loginHeader: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 22 },
  loginBtn: { width: '100%', marginTop: 14, background: '#E8A324', color: '#1B1D1F', border: 'none', padding: '11px 14px', borderRadius: 8, fontWeight: 700, fontSize: 14, cursor: 'pointer' },
  errBox: { display: 'flex', alignItems: 'center', gap: 6, background: '#FBEAE6', color: '#C1462E', padding: '8px 10px', borderRadius: 6, fontSize: 12.5, marginTop: 10 },
  demoToggle: { display: 'flex', alignItems: 'center', gap: 6, background: 'transparent', border: 'none', color: '#3E6E91', fontSize: 12.5, marginTop: 18, cursor: 'pointer', padding: 0 },
  demoBox: { marginTop: 10, background: '#F5F6F6', borderRadius: 8, padding: 10 },
  demoRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 12.5, padding: '4px 0' },
  demoDot: { width: 8, height: 8, borderRadius: 4, flexShrink: 0 },
  quickLoginBtn: { background: '#1B1D1F', color: '#F3F1EC', border: 'none', borderRadius: 5, padding: '3px 9px', fontSize: 11, cursor: 'pointer' },
};
